env:
  es2021: true
  node: true
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
plugins:
  - jest
rules: {
  no-console: off,
  import/extensions: off,
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для двух констант
}
